#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace ENGINE
{
	enum COMPONENTID { COMP_DYNAMIC, COMP_STATIC, COMP_END };
	enum BUFFERID { BUFFER_RCCOL, BUFFER_RCTEX, BUFFER_TRICOL, BUFFER_TRITEX, BUFFER_TERRAINTEX, BUFFER_CUBETEX,BUFFER_SKYBOX };
	enum INFO { INFO_RIGHT, INFO_UP, INFO_LOOK, INFO_POS, INFO_END };
	enum ROTATION { ROT_X, ROT_Y, ROT_Z, ROT_END };
	enum TEXTURETYPE { TEX_NORMAL, TEX_CUBE, TEX_END };
	enum RENDERID { RENDER_PRIORITY, RENDER_NONALPHA, RENDER_ALPHA, RENDER_UI, RENDER_END };
	enum COLLTYPE { COL_FALSE, COL_TRUE, COL_END };
	enum MESHTYPE { MESH_STATIC, MESH_DYNAMIC, MESH_NAVI, MESH_END };

}

#endif // Engine_Enum_h__
